/**
 * Botticelli DB
 * A database of people/creatures/characters for the game Boticelli.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ecapstone@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Fact model module.
 * @module model/Fact
 * @version 1.0.0
 */
class Fact {
    /**
     * Constructs a new <code>Fact</code>.
     * @alias module:model/Fact
     * @param text {String} 
     */
    constructor(text) { 
        
        Fact.initialize(this, text);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, text) { 
        obj['text'] = text;
    }

    /**
     * Constructs a <code>Fact</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Fact} obj Optional instance to populate.
     * @return {module:model/Fact} The populated <code>Fact</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Fact();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
Fact.prototype['id'] = undefined;

/**
 * @member {Date} updated_at
 */
Fact.prototype['updated_at'] = undefined;

/**
 * @member {Date} created_at
 */
Fact.prototype['created_at'] = undefined;

/**
 * @member {String} text
 */
Fact.prototype['text'] = undefined;






export default Fact;

